name: Move project indices to uv.toml
description: Reads all indices defined within your pyproject.toml and replaces the uv.toml ones
# Schema: https://json.schemastore.org/github-action.json

inputs:
  # Define the required input parameters for the action
  pyproject_toml_file:
    default: './pyproject.toml'
    required: false
    description: 'Path to pyproject.toml to use'

runs:
  using: 'composite'
  steps:
    - name: Add or replace to uv.toml
      shell: bash
      run: |      
        TMP="$(mktemp fileName.XXXXXXXX)"
        
        echo "using $TMP file for mods"
        
        cat $HOME/.config/uv/uv.toml 2>/dev/null \
          | yq -p toml 'del(.index)' | yj -yt > $TMP
            
        # append pyproject indices to the end of TMP file
        cat "${{ inputs.pyproject_toml_file }}" \
          | yq -p toml -o json '.tool.uv' \
          | jq '{index} | .index |= map(del(.explicit))' \
          | yj -jt >> $TMP
        
        mv $TMP $HOME/.config/uv/uv.toml
        
        mkdir -p /etc/uv/
        cat $HOME/.config/uv/uv.toml > /etc/uv/uv.toml
        echo "Successfully added project indices to uv.toml"
        cat $HOME/.config/uv/uv.toml
