name: Move project indices to uv.toml
description: Reads all indices defined within your pyproject.toml and replaces the uv.toml ones
# Schema: https://json.schemastore.org/github-action.json

inputs:
  # Define the required input parameters for the action
  pyproject_toml_file:
    default: './pyproject.toml'
    required: false
    description: 'Path to pyproject.toml to use'

runs:
  using: 'composite'
  steps:
    - name: Add or replace to uv.toml
      shell: bash
      run: |
        
        ls -alh $HOME/.config/uv
        
        ls -alh ./
        exit 1
        
        UV_TOML=$HOME/.config/uv/uv.toml
        PYPROJECT_TOML="${{ inputs.pyproject_toml_file }}"
  
        TMP="$(mktemp fileName.XXXXXXXX)"
        
        echo "using ${TMP} file for mods"
        
        cat ${UV_TOML} 2>/dev/null | yq -p toml 'del(.index)' > ${TMP}
        echo "filter in uv toml"
        cat ${UV_TOML} 2>/dev/null | yq -p toml 'del(.index)'
            
        # append pyproject indices to the end of TMP file
        cat ${PYPROJECT_TOML} | yq -p toml -o json '.tool.uv' | jq '{index} | .index |= map(del(.explicit))' | yj -jt >> ${TMP}
        echo "get indices ffrom pyproject"
        cat ${PYPROJECT_TOML} | yq -p toml -o json '.tool.uv' | jq '{index} | .index |= map(del(.explicit))' | yj -jt


        mv ${TMP} ${UV_TOML}
        echo "Successfully added project indices to uv.toml"
        cat ${UV_TOML}
