name: Move project indices to uv.toml
description: Reads all indices defined within your pyproject.toml and replaces the uv.toml ones
# Schema: https://json.schemastore.org/github-action.json

inputs:
  # Define the required input parameters for the action
  pyproject_toml_file:
    default: './pyproject.toml'
    required: false
    description: 'Path to pyproject.toml to use'

runs:
  using: 'composite'
  steps:
    - name: Add or replace to uv.toml
      shell: bash
      run: |
        echo "nix"