name: Login to pypi registry
description: Logs in into some registry
# Schema: https://json.schemastore.org/github-action.json

inputs:
  # Define the required input parameters for the action
  registry_url:
    description: "URL for image registry"
    required: true
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to ${{ inputs.registry_url }}
      id: login
      shell: bash
      run: |
        export FQDN="$(echo "${{ inputs.registry_url }}" | urlsplit netloc)"
        export PROT="$(echo "${{ inputs.registry_url }}" | urlsplit scheme)"

        echo "${{ inputs.registry_password }}" | keyring set "$FQDN" "${{ inputs.registry_username }}"

        mkdir -p "$HOME/.config/uv"
        export EXTRA_INDEX_URL="${PROT}://${{ inputs.registry_username }}@${FQDN}"
        cat "$HOME/.config/uv/uv.toml" 2>/dev/null \
          | dasel put -r toml -t string -v "${EXTRA_INDEX_URL}" 'extra-index-url.[]' \
          > "$HOME/.config/uv/uv.toml"

    - shell: bash
      run: echo "🔑 Successfully logged into ${{ inputs.registry_url}} (as ${{ inputs.registry_username }})."
