name: Login to pypi registry
description: Logs in into some registry
# Schema: https://json.schemastore.org/github-action.json

inputs:
  # Define the required input parameters for the action
  registry_url:
    description: "URL for image registry"
    required: true
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to ${{ inputs.registry_url }}
      id: login
      run: |        
        echo "${{ inputs.registry_password }}" \
          | uv auth login "${{ inputs.registry_url }}" --username ${{ inputs.registry_username }} --password - 

    - run: echo "🔑 Successfully logged into ${{ inputs.registry_url}} (as ${{ inputs.registry_username }})."
